version: '{build}'
os: Visual Studio 2015
install:
- set PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%
build:
  project: build.proj
  verbosity: normal
test_script:
- nunit3-console.exe bin\ReleaseTests\React.Tests\React.Tests.dll
artifacts:
- path: output\*.nupkg
